// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02DR-l-7UCyYgtYjN12VNeE4miKnFRvs',
    appId: '1:891059624673:web:3268af4bda5deb5a2d35a0',
    messagingSenderId: '891059624673',
    projectId: 'skincare-fd958',
    authDomain: 'skincare-fd958.firebaseapp.com',
    storageBucket: 'skincare-fd958.appspot.com',
    measurementId: 'G-0S5HQVLGVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-s-_iwBg5bSlng9knpIDmqam7_CFaPfM',
    appId: '1:891059624673:android:1b0b7246f4790ee52d35a0',
    messagingSenderId: '891059624673',
    projectId: 'skincare-fd958',
    storageBucket: 'skincare-fd958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9mgBB8fwcXVL0wDbZ74U_6mKIGuHmF3E',
    appId: '1:891059624673:ios:2d3fee7eda4d5b2c2d35a0',
    messagingSenderId: '891059624673',
    projectId: 'skincare-fd958',
    storageBucket: 'skincare-fd958.appspot.com',
    iosBundleId: 'com.example.skincareAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9mgBB8fwcXVL0wDbZ74U_6mKIGuHmF3E',
    appId: '1:891059624673:ios:c816a89f86633a652d35a0',
    messagingSenderId: '891059624673',
    projectId: 'skincare-fd958',
    storageBucket: 'skincare-fd958.appspot.com',
    iosBundleId: 'com.example.skincareAndroid.RunnerTests',
  );
}
